default:
  project_name: "books-of-ukraine"
  schema_name: "books_ukraine"
  
  # Database Configuration - Books of Ukraine Project
  # Ellis Pipeline stages:
  # - stage_0: Core foundation (books data only)
  # - stage_1: + Ukrainian administrative data
  # - stage_2: + Custom/extra data integration  
  # - main: Final analytical database (optimized for analysts)
  database:
    books_of_ukraine:
      main: "./data-private/derived/manipulation/SQLite/books-of-ukraine.sqlite"
      stage_0: "./data-private/derived/manipulation/SQLite/books-of-ukraine-0.sqlite"  
      stage_1: "./data-private/derived/manipulation/SQLite/books-of-ukraine-1.sqlite"
      stage_2: "./data-private/derived/manipulation/SQLite/books-of-ukraine-2.sqlite"
    directories:
      cache: "./ai/"
      derived: "./data-private/derived/"
      raw: "./data-private/raw/"
